#!/bin/bash
declare -A eng_phrases
eng_phrases=(
    ['festered']='to get to the point where something becomes rotten'
    ['itch to do']='compelled to do something'
    ['a storm was brewing']='bad things were coming'
    ['knuckle under']='give in'
    ['home spun']='made at home'
    ['spark an uprising']='to initiate something'
    ['dread']=' to hate to do something you need to do'
    ['cramming']='to put everything together in a  small time or space'
    ['break down/ split up']='to do things in sections instead of all at once (like pay roll)'
    ['soak']='remojar'
    ['soak in']='to remember something (retain info)'
    ['soak up ']=' retaining something'
    ['I am soaked']='completely wet'
    ['get around to it']='means with time you finish your task'
    ['put off']='postpone'
    ['stumble over your words']='you try but do not have a answer'
    ['split up']='devide or to break up (a couple)'
    ['road block']='somehting that stops you from going forward'
    ['in the zone']='to be in a state of mind to complete focus'
    ['throw up a wall of hate']='to exaggerate '
    ['profound']='deep in terms of strong and long lasting'
    ['emulated']='imitation of something'
    ['to crush']='destroy'
    ['enriched']='to make wealthy with knowledge of money'
    ['wreak havoc']='create a lot of disorder or chaos'
    ['surpass']='to go beyond the expected'
    ['do the dirty work']='the one who takes the blame and does the dishonest deeds'
    ['livid']='extremely angry'
    ['to break down ']='separate, to break down and became very angry=to lose a sense of clarity'
    ['to go to great lengths']='to do as much as you can to try to achieve a goal'
    ['a devastating blow']='very damaging '
    ['eek out ']='just barely finish or win'
    ['divulge']='spread'
    ['boasted']='to brag =to say you are the best or arrogantly proud'
    ['in the dark']='unknowing, hidden '
    ['seep out']='leaking info'
    ['thwarted']='stop a plan'
    ['demonize']='make people believe something is really bad'
    ['an insider']='someone who knows from experience '
    ['besieged']='to overwhelmed by or from something'
    ['confronted']='to be approached or questioned'
    ['back']='to support'
    ['soar']='to move quickly '
    ['undermine']='to secretly put blame on people who support'
    ['reneg']='a fancy way to LIAR'
    ['rescind']='take back a word or a promise'
    ['lick your wounds']='trying to recover'
    ['the Domino Theory'
    ['set off']='to start a series of events'
    ['prosper']='to move forward or become better'
    ['packed']='full'
    ['to pack']='to fill'
    ['fueling ']='anti']='communism'
    ['to perish']='to die'
    ['vanquish']='to send away or extract'
    ['side step']='to avoid'
    ['hold up']='to survive or continue to be able to do something and it can also mean a delay'
    ['point out']='means to highlight or put focus on an issue'
    ['take on']='accept'
    ['main squeeze']='the person you dating or married'
    ['to keep an eye on']='to care for something by looking after it'
    ['artificer']='a skilled craftsman or inventor.'
    ['tar ']='a dark, thick, flammable liquid distilled from wood or coal,
consisting of a mixture of hydrocarbons, resins, alcohols,
and other compounds. It is used in roadmaking and for coating and preserving timber.'
)
